# Generated by Django 6.0.2 on 2026-03-21 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id_todo', models.UUIDField(primary_key=True, serialize=False)),
                ('nom_todo', models.CharField(max_length=50)),
                ('dateCreate', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
    ]
